name: immich
services:
  database:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "999:999"
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: pg_isready -h 127.0.0.1 -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_DB_SRC}
        target: ${VOLUME_DB_DST}
        read_only: false
    shm_size: 128mb
    networks:
      - immich

  redis:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "568:568"
    image: docker.io/valkey/valkey:8.1.5-alpine3.23
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    volumes:
      - type: bind
        source: ${VOLUME_VALKEY_SRC}
        target: ${VOLUME_VALKEY_DST}
        read_only: false
    healthcheck:
      test: valkey-cli ping || exit 1
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 5s
    networks:
      - immich

  immich:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "568:568"
    image: ghcr.io/immich-app/immich-server:v2.5.5
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: Europe/Berlin
      DB_HOSTNAME: database
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE_NAME: ${POSTGRES_DB}
      REDIS_HOSTNAME: redis
    healthcheck:
      test: immich-healthcheck
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_LIBRARY_SRC}
        target: ${VOLUME_LIBRARY_DST}
        read_only: false
    networks:
      - immich
      - reverse-proxy

  immich-machine-learning:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    #user: "568:568"
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.5
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      MPLCONFIGDIR: ${VOLUME_ML_CACHE_DST}
    healthcheck:
      test: ["CMD", "python3", "healthcheck.py"]
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 5s
    volumes:
      - type: bind
        source: ${VOLUME_ML_CACHE_SRC}
        target: ${VOLUME_ML_CACHE_DST}
        read_only: false
    networks:
      - immich

networks:
  immich:
  reverse-proxy:
    external: true
    name: reverse-proxy
